# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad841a767fd490259ac3315d5c79b1632f948ad495a0c0135bcff7882c2ea2cc74e5d33a619776f39fdebda15cde9d9f8d038a28471b61ab3580b4ce7bc61427

test:
  secret_key_base: e2c064580dc4e7d6145ee9ba0191e1114f123dbaced36e3a3449f93211c07eec4b89cf26a478f20d6c5f63f6a3a2648fadd10d16bfb0dcc2c27febee04040864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
